# Generated by Django 2.2.5 on 2019-09-29 18:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo_main',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 29, 18, 10, 53, 664243, tzinfo=utc)),
        ),
    ]
