# Generated by Django 2.2.5 on 2019-09-30 04:59

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190929_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_main',
            field=models.ImageField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='property',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 30, 4, 59, 55, 423266, tzinfo=utc)),
        ),
    ]
