# Generated by Django 2.2.5 on 2019-10-01 05:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20190930_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], max_length=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 1, 5, 34, 7, 22827, tzinfo=utc)),
        ),
    ]
