# Generated by Django 2.2.6 on 2019-10-05 06:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20191005_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='published',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 10, 5, 6, 36, 6, 243913, tzinfo=utc)),
        ),
    ]
