# Generated by Django 2.2.6 on 2019-10-05 06:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20191005_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='published',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 10, 5, 6, 38, 51, 586295, tzinfo=utc)),
        ),
    ]
