# Generated by Django 2.2.6 on 2019-10-06 06:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20191005_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='published',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 10, 6, 6, 31, 5, 283649, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='listings.Property')),
            ],
        ),
    ]
