# Generated by Django 2.2.6 on 2019-10-06 12:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20191006_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='events',
            name='photo',
            field=models.FileField(upload_to='pics/events'),
        ),
        migrations.AlterField(
            model_name='property',
            name='published',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 10, 6, 12, 1, 4, 640929, tzinfo=utc)),
        ),
    ]
